---
# Copyright 2016 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ----------------------------------------------------------------------------
# Solution Specific Configurations details
# ----------------------------------------------------------------------------
reference-architecture:
      db2_mini_playbook:
        description: Playbook for installing db2 warehouse Mini
# dashDB Node roles
        db2_nodes_layout: "scripts/db2_nodes.cfg"
        db2_image_selection: db2_local_image  # Select db2Local image location: "db2_local_image" or  "db2_online_image"
        db2_local_files: "packages/db2local/*.tar"
        db2_online_dockerhub: {name: "dockerID" , password: "docker_password"}

# Cluster File System / Disk layout
        gpfs_install: "packages/gpfs/*.deb"
        gpfs_nodes_layout: "scripts/gpfs-fpo-node.cfg"
        gpfs_disks_layout: "scripts/gpfs-fpo-pool_ConfigA.cfg"
        gpfs_clusterfs_mnt: "/mnt/clusterfs"

# DockerVG , recommended for High Performance Docker deployment
# dockerpool can reside on saparate LVM (not yet support in this deployment script)
        dockerpool_disk: "/dev/sdb"


# ----------------------------------------------------------------------------
# Network details
# ----------------------------------------------------------------------------

ipaddr-mgmt-network: 192.168.3.0/24
ipaddr-mgmt-switch:
    rack1: 192.168.3.5
ipaddr-data-switch:
    rack1: 9.3.3.178
redundant-network: false
userid-default: ubuntu
password-default: passw0rd
userid-mgmt-switch: admin
password-mgmt-switch: admin
userid-data-switch: admin
password-data-switch: admin
networks:
    external:
        description: Organization site or external 1G network
        addr: 9.3.3.0/24
        broadcast: 9.3.3.255
        gateway: 9.3.3.1
        dns-nameservers: 9.3.1.200
        dns-search: aus.stglabs.ibm.com
        method: static
        eth-port: eth10
    interconnect:
        description: Private HighSpeed Data Network to Interconnect Cluster
        addr: 10.10.10.0/24
        broadcast: 10.0.0.255
        method: static
        eth-port: eth11
    mgmt-pxe:
        description: Management Network
        method: dhcp
        eth-port: eth15


# ----------------------------------------------------------------------------
# Server NODE TEMPLATE
# ----------------------------------------------------------------------------

node-templates:
# ----------------------------------------------------------------------------
# DB2 node
# ----------------------------------------------------------------------------
    compute-1:
        hostname: bluhelix # will be named by Genesis as: mnode-1, mnode-2, etc...
        userid-ipmi: ADMIN
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        os-disk:
            - /dev/sda
#            - /dev/sdb

        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
        ports:
            ipmi:
                rack1:
                    - 1
            pxe:
                rack1:
                    - 18

            eth10:
                rack1:
                    - 1
            eth11:
                rack1:
                    - 1

        networks:
            - external
            - interconnect
            - mgmt-pxe
